# modules/holochain-edgenode.nix
#
# Core module: NixOS service for a Holochain conductor (in-process lair keystore)
# plus an idempotent hApp installer.
#
# The module supports both supported Holochain lines. Everything that differs
# between them is derived from `cfg.package.version`, and every command and
# config key below was verified against the pinned holonix binaries
# (`holochain`/`hc` 0.7.0 and 0.6.3) rather than taken from documentation.
# See docs/architecture.md for the probe transcripts.
#
# The passphrase and readiness handling follows Holo-Host/holo-host
# `nix/modules/nixos/holochain/default.nix` (ADR-016).
{
  config,
  lib,
  pkgs,
  inputs,
  ...
}: let
  cfg = config.services.holochain-edgenode;

  # The one fact everything version-dependent is derived from.
  isPre07 = lib.versionOlder cfg.package.version "0.7";

  # 0.6 defaults: Holo-Host/edgenode docker/conductor-config-0.6.1.template.yaml.
  # 0.7 defaults: `holochain --create-config` of 0.7.0.
  defaultBootstrapUrl =
    if isPre07
    then "https://dev-test-bootstrap2.holochain.org"
    else "https://dev-test-bootstrap2.holochain.org/";
  defaultSignalUrl = "wss://dev-test-bootstrap2.holochain.org";
  defaultRelayUrl = "https://use1-1.relay.n0.iroh-canary.iroh.link./";

  bootstrapUrl =
    if cfg.bootstrapUrl != null
    then cfg.bootstrapUrl
    else defaultBootstrapUrl;
  signalUrl =
    if cfg.signalUrl != null
    then cfg.signalUrl
    else defaultSignalUrl;
  relayUrl =
    if cfg.relayUrl != null
    then cfg.relayUrl
    else defaultRelayUrl;

  # `signal_url` is not a key in the 0.7 schema and the conductor rejects it.
  # `relay_url` is required on BOTH lines: a 0.6.3 conductor given only
  # bootstrap_url and signal_url refuses to start with
  # `network: missing field `relay_url``.
  networkSection =
    if isPre07
    then ''
      network:
        bootstrap_url: ${bootstrapUrl}
        signal_url: ${signalUrl}
        relay_url: ${relayUrl}
    ''
    else ''
      network:
        bootstrap_url: ${bootstrapUrl}
        relay_url: ${relayUrl}
    '';

  # The lair keystore opens a unix socket at <lair_root>/socket, and unix socket
  # paths are capped at SUN_LEN (108 bytes). A deep dataDir makes the conductor
  # die with `path must be shorter than SUN_LEN` and no mention of the config.
  lairRoot = "${cfg.dataDir}/ks";
  passphraseFile = "${cfg.dataDir}/${cfg.passphraseFileName}";

  conductorConfig = pkgs.writeText "conductor-config.yaml" ''
    # Generated by the holochain-edgenode NixOS module. Do not edit by hand.
    data_root_path: ${cfg.dataDir}
    keystore:
      type: lair_server_in_proc
      lair_root: ${lairRoot}
    admin_interfaces:
      - driver:
          type: websocket
          port: ${toString cfg.adminPort}
          allowed_origins: "${cfg.allowedOrigins}"
    ${networkSection}'';

  # 0.7 dispatches admin calls through `hc client call --port <p>`. On 0.6 that
  # subcommand does not exist at all (`hc` 0.6.3 panics looking for an external
  # `hc-client`); the equivalent is `hc sandbox call --running <p>`. Every
  # sub-subcommand below it takes identical arguments on both lines, so the
  # prefix is the only thing that has to be line-aware.
  callPrefix =
    if isPre07
    then "hc sandbox call --running ${toString cfg.adminPort}"
    else "hc client call --port ${toString cfg.adminPort}";

  happInstaller = pkgs.writeShellApplication {
    name = "holochain-happ-installer";
    runtimeInputs = [cfg.hcPackage pkgs.coreutils pkgs.gnugrep];
    text = ''
      call() { ${callPrefix} "$@"; }

      # The admin interface answers only once the conductor is ready; list-apps is
      # the cheapest probe that proves the socket is usable rather than just open.
      ready=0
      for _ in $(seq 1 ${toString cfg.installerTimeout}); do
        if call list-apps > /dev/null 2>&1; then
          ready=1
          break
        fi
        sleep 1
      done
      if [ "$ready" -ne 1 ]; then
        echo "admin interface on port ${toString cfg.adminPort} did not answer list-apps within ${toString cfg.installerTimeout}s" >&2
        exit 1
      fi

      ${lib.concatStringsSep "\n" (lib.mapAttrsToList (name: happ: ''
          # ---- ${name} ----
          if call list-apps | grep -q ${lib.escapeShellArg ''"installed_app_id":"${name}"''}; then
            echo "hApp ${name} is already installed, skipping install-app"
          else
            call install-app --app-id ${lib.escapeShellArg name} \
              ${happ.src}${lib.optionalString (happ.networkSeed != null) " ${lib.escapeShellArg happ.networkSeed}"}
          fi

          # enable-app on an already-enabled app exits 0 on both lines, so this
          # runs on every boot and is what makes "always enabled" true.
          call enable-app ${lib.escapeShellArg name}

          if ! call list-apps | grep -q ${lib.escapeShellArg ''"installed_app_id":"${name}"''}; then
            echo "hApp ${name} is not listed after install and enable" >&2
            exit 1
          fi
        '')
        (lib.filterAttrs (_: happ: happ.installed) cfg.happs))}

      # add-app-ws is NOT idempotent: a second call on the same port fails with
      # AddrInUse. Consult list-app-ws first so a reboot does not fail the unit.
      if call list-app-ws | grep -q ${lib.escapeShellArg ''"port":${toString cfg.appPort}''}; then
        echo "app websocket already attached on port ${toString cfg.appPort}"
      else
        call add-app-ws ${toString cfg.appPort} --allowed-origins ${lib.escapeShellArg cfg.allowedOrigins}
      fi
    '';
  };
in {
  options.services.holochain-edgenode = {
    enable = lib.mkEnableOption "Holochain edgenode (conductor + lair + hApp installer)";

    package = lib.mkOption {
      type = lib.types.package;
      default = inputs.holonix.packages.${pkgs.system}.holochain;
      defaultText = lib.literalExpression "inputs.holonix.packages.\${pkgs.system}.holochain";
      description = ''
        Holochain conductor package. Its `version` selects the config schema the
        module renders: below 0.7 the network section carries `bootstrap_url`,
        `signal_url` and `relay_url`; from 0.7 it carries `bootstrap_url` and
        `relay_url`, because `signal_url` was removed from the schema.
      '';
    };

    hcPackage = lib.mkOption {
      type = lib.types.package;
      default = inputs.holonix.packages.${pkgs.system}.hc;
      defaultText = lib.literalExpression "inputs.holonix.packages.\${pkgs.system}.hc";
      description = ''
        Holochain CLI package used by the hApp installer. Keep it on the same
        line as `package`: the admin subcommand is `hc client call` from 0.7 and
        `hc sandbox call` below it.
      '';
    };

    user = lib.mkOption {
      type = lib.types.str;
      default = "holochain";
      description = "System user the conductor runs as.";
    };

    dataDir = lib.mkOption {
      type = lib.types.path;
      default = "/var/lib/holochain";
      description = ''
        Persistent state directory for the conductor database, the lair keystore
        and the generated passphrase. Created as the unit's `StateDirectory` with
        mode 0700.

        Keep it short. The keystore's unix socket is `''${dataDir}/ks/socket` and
        unix socket paths are capped at 108 bytes (`SUN_LEN`); a deeper path makes
        the conductor exit at startup with `path must be shorter than SUN_LEN`.
      '';
    };

    passphraseFileName = lib.mkOption {
      type = lib.types.str;
      default = "lair-passphrase";
      description = ''
        Name of the lair passphrase file inside `dataDir`. Generated with mode
        0600 on first boot if absent and reused on every boot after that, which
        is what lets the keystore open again after a reboot with nobody present.
      '';
    };

    adminPort = lib.mkOption {
      type = lib.types.port;
      default = 4444;
      description = "WebSocket port for the conductor admin interface (bound to localhost).";
    };

    appPort = lib.mkOption {
      type = lib.types.port;
      default = 8888;
      description = "WebSocket port the hApp installer attaches as the app interface.";
    };

    allowedOrigins = lib.mkOption {
      type = lib.types.str;
      default = "*";
      description = ''
        Allowed origins for the admin and app WebSocket interfaces: `*`, a single
        origin, or a comma-separated list. With `*` no `--origin` header is needed
        on the admin call.
      '';
    };

    bootstrapUrl = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      description = ''
        Kitsune2 bootstrap server used for WAN peer discovery. `null` selects the
        default for the configured line: `https://dev-test-bootstrap2.holochain.org`
        below 0.7 (Holo-Host/edgenode's 0.6.1 template) and the same URL with a
        trailing slash from 0.7 (what `holochain --create-config` writes). No
        production bootstrap URL is documented for either line, so point this at
        your own infrastructure for a real deployment.
      '';
    };

    signalUrl = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      description = ''
        WebRTC signal server. Used only below 0.7, where `null` selects
        `wss://dev-test-bootstrap2.holochain.org`. `network.signal_url` was
        removed from the 0.7 config schema, so from 0.7 this option is ignored
        and setting it raises a warning; use `relayUrl` instead.
      '';
    };

    relayUrl = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      description = ''
        Iroh relay used when a direct connection cannot be established. Required
        by the conductor on both lines; `null` selects
        `https://use1-1.relay.n0.iroh-canary.iroh.link./`, the default both
        0.6.3 and 0.7.0 write for themselves.
      '';
    };

    installerTimeout = lib.mkOption {
      type = lib.types.int;
      default = 300;
      description = ''
        Seconds the hApp installer waits for the admin interface to answer before
        failing. The conductor needs about 80 seconds to open the port on an
        unaccelerated VM, so leave room.
      '';
    };

    useSystemdNotify = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Run the conductor as `Type = "notify"`, so the unit becomes active only
        once the conductor has signalled readiness rather than as soon as the
        process exists. Set to false to fall back to `Type = "simple"`.
      '';
    };

    happs = lib.mkOption {
      type = lib.types.attrsOf (lib.types.submodule {
        options = {
          src = lib.mkOption {
            type = lib.types.path;
            description = "Path to the `.happ` bundle. Fetch it by hash; never commit one (ADR-012).";
          };
          installed = lib.mkOption {
            type = lib.types.bool;
            default = true;
            description = "Whether to install and enable this hApp.";
          };
          networkSeed = lib.mkOption {
            type = lib.types.nullOr lib.types.str;
            default = null;
            description = "Network seed override for every DNA in this app.";
          };
        };
      });
      default = {};
      description = "hApps to install and keep enabled, keyed by installed app id.";
      example = lib.literalExpression ''
        {
          dino-adventure = {
            src = pkgs.fetchurl {
              url = "https://github.com/holochain/dino-adventure/releases/download/v0.3.0/dino-adventure-v0.3.0.happ";
              sha256 = "...";
            };
            networkSeed = "workshop-2026";
          };
        }
      '';
    };

    metricsExporter = {
      enable = lib.mkEnableOption "Prometheus node_exporter for fleet observability";

      port = lib.mkOption {
        type = lib.types.port;
        default = 9100;
        description = "Port to expose node metrics on.";
      };
    };

    openFirewall = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Open firewall ports for the admin, app and metrics interfaces. The
        conductor binds its websockets to localhost, so this only matters for
        the metrics exporter unless `danger_bind_addr` is configured by hand.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    warnings =
      lib.optional (!isPre07 && cfg.signalUrl != null)
      "services.holochain-edgenode.signalUrl is set, but network.signal_url was removed from the Holochain 0.7 config schema and is ignored. Use services.holochain-edgenode.relayUrl instead.";

    users.users.${cfg.user} = {
      isSystemUser = true;
      group = cfg.user;
      home = cfg.dataDir;
    };
    users.groups.${cfg.user} = {};

    systemd.services.holochain-conductor = {
      description = "Holochain conductor";
      wantedBy = ["multi-user.target"];
      after = ["network-online.target"];
      wants = ["network-online.target"];

      # ADR-016: the passphrase is generated into the state directory, never into
      # the Nix store, so it survives a reboot and never becomes world-readable.
      preStart = ''
        umask 077
        if [ ! -s ${lib.escapeShellArg passphraseFile} ]; then
          echo "generating a new lair passphrase at ${passphraseFile}"
          head -c 32 /dev/urandom | base64 | tr -d '\n' > ${lib.escapeShellArg passphraseFile}
          chmod 0600 ${lib.escapeShellArg passphraseFile}
        else
          echo "using the existing lair passphrase at ${passphraseFile}"
        fi
      '';

      script = ''
        exec ${lib.getExe' cfg.package "holochain"} \
          --piped \
          --config-path ${conductorConfig} \
          < ${lib.escapeShellArg passphraseFile}
      '';

      serviceConfig =
        {
          User = cfg.user;
          Group = cfg.user;
          StateDirectory = baseNameOf cfg.dataDir;
          StateDirectoryMode = "0700";
          WorkingDirectory = cfg.dataDir;
          Restart = "on-failure";
          RestartSec = "5s";
          UMask = "0077";
        }
        // (
          if cfg.useSystemdNotify
          then {
            Type = "notify";
            NotifyAccess = "all";
            # The conductor takes well over a minute to come up on an
            # unaccelerated VM; the default 90s would kill it mid-startup.
            TimeoutStartSec = "600s";
          }
          else {Type = "simple";}
        );
    };

    systemd.services.holochain-happ-installer = lib.mkIf (cfg.happs != {}) {
      description = "Install and enable the configured hApps in the Holochain conductor";
      after = ["holochain-conductor.service"];
      requires = ["holochain-conductor.service"];
      wantedBy = ["multi-user.target"];

      serviceConfig = {
        Type = "oneshot";
        User = cfg.user;
        Group = cfg.user;
        WorkingDirectory = cfg.dataDir;
        RemainAfterExit = true;
        ExecStart = lib.getExe happInstaller;
        TimeoutStartSec = "600s";
      };
    };

    services.prometheus.exporters.node = lib.mkIf cfg.metricsExporter.enable {
      enable = true;
      port = cfg.metricsExporter.port;
      enabledCollectors = ["systemd"];
    };

    networking.firewall = lib.mkIf cfg.openFirewall {
      allowedTCPPorts =
        [cfg.adminPort cfg.appPort]
        ++ lib.optional cfg.metricsExporter.enable cfg.metricsExporter.port;
    };
  };
}
