# modules/holochain-edgenode.nix
#
# Core module: NixOS service for a Holochain conductor + lair keystore + hApp installer.
# Import this module in your nixosConfiguration, then set services.holochain-edgenode.enable = true.
{ config, lib, pkgs, inputs, ... }:

let
  cfg = config.services.holochain-edgenode;
  conductorConfig = pkgs.writeText "conductor-config.yaml" ''
    # Generated by holochain-edgenode module — do not edit by hand
    data_root_path: ${cfg.dataDir}
    keystore:
      type: lair_server_in_proc
    admin_interfaces:
      - driver:
          type: websocket
          port: ${toString cfg.adminPort}
          allowed_origins: ${cfg.allowedOrigins}
    network:
      bootstrap_url: ${cfg.bootstrapUrl}
      signal_url: ${cfg.signalUrl}
  '';
in
{
  options.services.holochain-edgenode = {
    enable = lib.mkEnableOption "Holochain edgenode (conductor + lair + hApp installer)";

    package = lib.mkOption {
      type = lib.types.package;
      default = inputs.holonix.packages.${pkgs.system}.holochain;
      description = "Holochain conductor package.";
    };

    hcPackage = lib.mkOption {
      type        = lib.types.package;
      default     = inputs.holonix.packages.${pkgs.system}.hc;
      description = "Holochain CLI package used by the hApp installer. Validate the package name against the pinned holonix commit — it may differ across holonix versions.";
    };

    user = lib.mkOption {
      type = lib.types.str;
      default = "holochain";
      description = "System user the conductor runs as.";
    };

    dataDir = lib.mkOption {
      type = lib.types.path;
      default = "/var/lib/holochain";
      description = "Persistent state directory for conductor and lair keystore.";
    };

    adminPort = lib.mkOption {
      type = lib.types.port;
      default = 4444;
      description = "WebSocket port for conductor admin interface.";
    };

    appPort = lib.mkOption {
      type = lib.types.port;
      default = 8888;
      description = "WebSocket port for conductor app interface.";
    };

    allowedOrigins = lib.mkOption {
      type = lib.types.str;
      default = "*";
      description = "Allowed origins for admin WebSocket connections.";
    };

    bootstrapUrl = lib.mkOption {
      type = lib.types.str;
      default = "https://bootstrap.holo.host";
      description = "Holochain bootstrap server URL.";
    };

    signalUrl = lib.mkOption {
      type = lib.types.str;
      default = "wss://signal.holo.host";
      description = "Holochain WebRTC signal server URL.";
    };

    happs = lib.mkOption {
      type = lib.types.attrsOf (lib.types.submodule {
        options = {
          src = lib.mkOption {
            type = lib.types.path;
            description = "Path to the .happ bundle.";
          };
          installed = lib.mkOption {
            type = lib.types.bool;
            default = true;
            description = "Whether to install this hApp at first boot.";
          };
          networkSeed = lib.mkOption {
            type = lib.types.nullOr lib.types.str;
            default = null;
            description = "Network seed to use when installing the hApp.";
          };
        };
      });
      default = {};
      description = "hApps to install at first boot, keyed by app id.";
      example = lib.literalExpression ''
        {
          windtunnel = {
            src = ./happs/windtunnel.happ;
            networkSeed = "workshop-2026";
          };
          moss = {
            src = ./happs/moss.happ;
            networkSeed = "sensorica-moss-2026";
          };
        }
      '';
    };

    openFirewall = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Open firewall ports for admin and app interfaces.";
    };
  };

  config = lib.mkIf cfg.enable {
    users.users.${cfg.user} = {
      isSystemUser = true;
      group = cfg.user;
      home = cfg.dataDir;
      createHome = true;
    };
    users.groups.${cfg.user} = {};

    systemd.services.holochain-conductor = {
      description = "Holochain conductor";
      wantedBy = [ "multi-user.target" ];
      after = [ "network-online.target" ];
      wants = [ "network-online.target" ];

      serviceConfig = {
        Type = "simple";
        User = cfg.user;
        Group = cfg.user;
        WorkingDirectory = cfg.dataDir;
        ExecStart = "${cfg.package}/bin/holochain --config-path ${conductorConfig}";
        Restart = "on-failure";
        RestartSec = "5s";
      };
    };

    systemd.services.holochain-happ-installer = lib.mkIf (cfg.happs != {}) {
      description = "Install configured hApps into the Holochain conductor";
      after    = [ "holochain-conductor.service" ];
      wantedBy = [ "multi-user.target" ];

      path = [ cfg.hcPackage pkgs.netcat-gnu pkgs.coreutils ];

      serviceConfig = {
        Type            = "oneshot";
        User            = cfg.user;
        RemainAfterExit = true;
        ExecStartPre    = toString (pkgs.writeShellScript "wait-for-conductor" ''
          timeout=60
          elapsed=0
          until nc -z 127.0.0.1 ${toString cfg.adminPort}; do
            sleep 1
            elapsed=$((elapsed + 1))
            if [ "$elapsed" -ge "$timeout" ]; then
              echo "Conductor did not open port ${toString cfg.adminPort} within ''${timeout}s" >&2
              exit 1
            fi
          done
        '');
      };

      # If hc CLI lacks these subcommands for the pinned holonix version, see §4.5 of
      # .local/nixos-holochain-architecture-design-2026-05-13.md for the Node.js fallback.
      script =
        lib.concatStringsSep "\n" (lib.mapAttrsToList (name: happCfg: ''
          hc app install \
            --admin-ws-url ws://127.0.0.1:${toString cfg.adminPort} \
            --app-id ${lib.escapeShellArg name} \
            --path ${happCfg.src} \
            ${lib.optionalString (happCfg.networkSeed != null)
              "--network-seed ${lib.escapeShellArg happCfg.networkSeed}"} \
            || echo "WARNING: install of ${name} failed (may already be installed)"
          hc app enable \
            --admin-ws-url ws://127.0.0.1:${toString cfg.adminPort} \
            --app-id ${lib.escapeShellArg name} \
            || true
        '') cfg.happs)
        + ''
          hc app attach-interface \
            --admin-ws-url ws://127.0.0.1:${toString cfg.adminPort} \
            --port ${toString cfg.appPort} \
            || true
        '';
    };

    networking.firewall = lib.mkIf cfg.openFirewall {
      allowedTCPPorts = [ cfg.adminPort cfg.appPort ];
    };
  };
}
