# modules/holochain-edgenode.nix
#
# Core module: NixOS service for a Holochain conductor (in-process lair keystore)
# plus an idempotent hApp installer.
#
# The module supports both supported Holochain lines. Everything that differs
# between them is derived from `cfg.package.version`, and every command and
# config key below was verified against the pinned holonix binaries
# (`holochain`/`hc` 0.7.0 and 0.6.3) rather than taken from documentation.
# See docs/architecture.md for the probe transcripts.
#
# The passphrase and readiness handling follows Holo-Host/holo-host
# `nix/modules/nixos/holochain/default.nix` (ADR-016).
{
  config,
  lib,
  pkgs,
  inputs,
  ...
}: let
  cfg = config.services.holochain-edgenode;

  # The one fact everything version-dependent is derived from.
  isPre07 = lib.versionOlder cfg.package.version "0.7";

  # 0.6 defaults: Holo-Host/edgenode docker/conductor-config-0.6.1.template.yaml.
  # 0.7 defaults: `holochain --create-config` of 0.7.0.
  defaultBootstrapUrl =
    if isPre07
    then "https://dev-test-bootstrap2.holochain.org"
    else "https://dev-test-bootstrap2.holochain.org/";
  defaultSignalUrl = "wss://dev-test-bootstrap2.holochain.org";
  defaultRelayUrl = "https://use1-1.relay.n0.iroh-canary.iroh.link./";

  bootstrapUrl =
    if cfg.bootstrapUrl != null
    then cfg.bootstrapUrl
    else defaultBootstrapUrl;
  signalUrl =
    if cfg.signalUrl != null
    then cfg.signalUrl
    else defaultSignalUrl;
  relayUrl =
    if cfg.relayUrl != null
    then cfg.relayUrl
    else defaultRelayUrl;

  # Kitsune2 module config the conductor merges under the keys it sets itself
  # (`NetworkConfig::to_k2_config`, holochain 0.6.3 and 0.7.0). Rendered as
  # JSON, which is YAML.
  advancedConfig = lib.optionalAttrs cfg.relayAllowPlainText {
    irohTransport.relayAllowPlainText = true;
  };

  # `signal_url` is not a key in the 0.7 schema and the conductor rejects it.
  # `relay_url` is required on BOTH lines: a 0.6.3 conductor given only
  # bootstrap_url and signal_url refuses to start with
  # `network: missing field `relay_url``. `request_timeout_s` sits under
  # `network` on both lines (0.6.3 already had it there).
  networkSection = lib.concatStringsSep "\n" (
    [
      "network:"
      "  bootstrap_url: ${bootstrapUrl}"
    ]
    ++ lib.optional isPre07 "  signal_url: ${signalUrl}"
    ++ ["  relay_url: ${relayUrl}"]
    ++ lib.optional (cfg.requestTimeoutS != null) "  request_timeout_s: ${toString cfg.requestTimeoutS}"
    ++ lib.optional (advancedConfig != {}) "  advanced: ${builtins.toJSON advancedConfig}"
  );

  # Top-level keys that exist only from 0.7: `db_sync_level` replaced 0.6's
  # `db_sync_strategy`, and `wasm_backend` is new. Both are rejected below
  # 0.7, so they are dropped there with a warning.
  topLevelSection = lib.concatStringsSep "\n" (
    lib.optional (!isPre07 && cfg.dbSyncLevel != null) "db_sync_level: ${cfg.dbSyncLevel}"
    ++ lib.optional (!isPre07 && cfg.wasmBackend != null) "wasm_backend: ${cfg.wasmBackend}"
  );

  # The lair keystore opens a unix socket at <lair_root>/socket, and unix socket
  # paths are capped at SUN_LEN (108 bytes). A deep dataDir makes the conductor
  # die with `path must be shorter than SUN_LEN` and no mention of the config.
  lairRoot = "${cfg.dataDir}/ks";

  # systemd creates the state directory, and only under /var/lib; an assertion
  # below rejects any other dataDir rather than leave it uncreated.
  stateDirectory = lib.removePrefix "/var/lib/" (toString cfg.dataDir);
  passphraseFile = "${cfg.dataDir}/${cfg.passphraseFileName}";

  conductorConfig = pkgs.writeText "conductor-config.yaml" ''
    # Generated by the holochain-edgenode NixOS module. Do not edit by hand.
    data_root_path: ${cfg.dataDir}
    keystore:
      type: lair_server_in_proc
      lair_root: ${lairRoot}
    admin_interfaces:
      - driver:
          type: websocket
          port: ${toString cfg.adminPort}
          allowed_origins: "${cfg.adminAllowedOrigins}"
    ${networkSection}
    ${topLevelSection}
  '';

  # 0.7 dispatches admin calls through `hc client call --port <p>`. On 0.6 that
  # subcommand does not exist at all (`hc` 0.6.3 panics looking for an external
  # `hc-client`); the equivalent is `hc sandbox call --running <p>`. Every
  # sub-subcommand below it takes identical arguments on both lines, so the
  # prefix is the only thing that has to be line-aware.
  callPrefix =
    if isPre07
    then "hc sandbox call --running ${toString cfg.adminPort}"
    else "hc client call --port ${toString cfg.adminPort}";

  happInstaller = pkgs.writeShellApplication {
    name = "holochain-happ-installer";
    runtimeInputs = [cfg.hcPackage pkgs.coreutils pkgs.jq];
    text = ''
      timeout=${toString cfg.installerTimeout}

      call() { ${callPrefix} "$@"; }

      # Empty when the app is not installed, otherwise its status: "enabled",
      # "disabled", and so on. list-apps returns JSON on both lines. Empty, not
      # a failure, when the call itself fails: the conductor answers slowly
      # while it compiles wasm, and under `set -e` a failed call here would end
      # the poll below on its first miss instead of retrying.
      app_status() {
        call list-apps 2>/dev/null \
          | jq -r --arg id "$1" '.[] | select(.installed_app_id == $id) | .status.type' 2>/dev/null \
          || true
      }

      # Installing or enabling a hApp makes the conductor compile the app's wasm,
      # which on a small machine takes longer than the admin client's own request
      # deadline: the call returns `Websocket error: Timeout` while the conductor
      # carries on and finishes. So the exit status of a call is not evidence
      # either way, and the outcome is polled instead.
      await_status() {
        id=$1
        want=$2
        for _ in $(seq 1 "$timeout"); do
          got=$(app_status "$id")
          if [ "$want" = "installed" ] && [ -n "$got" ]; then return 0; fi
          if [ "$got" = "$want" ]; then return 0; fi
          sleep 1
        done
        echo "hApp $id never reached '$want' within ''${timeout}s (last status: '$(app_status "$id")')" >&2
        exit 1
      }

      # The admin interface answers only once the conductor is ready; list-apps is
      # the cheapest probe that proves the socket is usable rather than just open.
      ready=0
      for _ in $(seq 1 "$timeout"); do
        if call list-apps > /dev/null 2>&1; then
          ready=1
          break
        fi
        sleep 1
      done
      if [ "$ready" -ne 1 ]; then
        echo "admin interface on port ${toString cfg.adminPort} did not answer list-apps within ''${timeout}s" >&2
        exit 1
      fi

      ${lib.concatStringsSep "\n" (lib.mapAttrsToList (name: happ: ''
          # ---- ${name} ----
          if [ -n "$(app_status ${lib.escapeShellArg name})" ]; then
            echo "hApp ${name} is already installed, skipping install-app"
          else
            call install-app --app-id ${lib.escapeShellArg name} \
              ${happ.src}${lib.optionalString (happ.networkSeed != null) " ${lib.escapeShellArg happ.networkSeed}"} \
              || echo "install-app for ${name} did not return cleanly; verifying below" >&2
            await_status ${lib.escapeShellArg name} installed
          fi

          # enable-app on an already-enabled app exits 0 on both lines, so this
          # runs on every boot and is what makes "always enabled" true.
          call enable-app ${lib.escapeShellArg name} \
            || echo "enable-app for ${name} did not return cleanly; verifying below" >&2
          await_status ${lib.escapeShellArg name} enabled
        '')
        (lib.filterAttrs (_: happ: happ.installed) cfg.happs))}

      # add-app-ws is NOT idempotent: a second call on the same port fails with
      # AddrInUse. Consult list-app-ws first so a reboot does not fail the unit.
      if call list-app-ws | jq -e --argjson p ${toString cfg.appPort} 'any(.[]; .port == $p)' > /dev/null; then
        echo "app websocket already attached on port ${toString cfg.appPort}"
      else
        call add-app-ws ${toString cfg.appPort} --allowed-origins ${lib.escapeShellArg cfg.allowedOrigins}
      fi
    '';
  };

  # ---- conductor metrics ----------------------------------------------------
  #
  # node_exporter's textfile collector reads every *.prom in one directory on
  # each scrape, so exporting a conductor-level series is a matter of writing
  # that file on a timer. The alternative, a long-lived exporter process holding
  # an admin websocket open, would be one more thing to supervise for no gain.

  textfileDir = cfg.metricsExporter.textfileDirectory;
  conductorMetricsFile = "${textfileDir}/holochain-conductor.prom";
  conductorCountersFile = "${cfg.dataDir}/conductor-metrics-counters.json";
  # [.] rather than an escaped dot: the flag reaches ExecStart unquoted, and
  # systemd would parse a backslash as an escape sequence of its own.
  systemdUnitExclude = ".+[.](device|scope|slice)";

  conductorMetricsScript = pkgs.writeShellApplication {
    name = "holochain-conductor-metrics";
    runtimeInputs = [cfg.hcPackage pkgs.coreutils pkgs.jq];
    text = ''
      out=${lib.escapeShellArg conductorMetricsFile}
      tmp="$out.tmp"

      # A conductor that is starting, restarting or wedged must not delete the
      # series: it reports holochain_conductor_up 0 and leaves every other
      # gauge at its zero value, which is what makes a dead node visible on the
      # dashboard rather than absent from it. 15 s is generous for a call over
      # a loopback websocket; anything slower is a conductor that is not well.
      if stats=$(timeout 15 ${callPrefix} dump-network-stats 2>/dev/null) \
        && printf '%s' "$stats" | jq -e . > /dev/null 2>&1; then
        up=1
      else
        up=0
        stats='{}'
      fi

      # null, not [], when the call fails: an unanswered list-apps must not
      # read as a conductor with no apps.
      if ! { apps=$(timeout 15 ${callPrefix} list-apps 2>/dev/null) \
        && printf '%s' "$apps" | jq -e 'type == "array"' > /dev/null 2>&1; }; then
        apps=null
      fi
      # The reply carries every DNA's properties and reaches jq below as one
      # command-line argument, which Linux caps at 128 KiB (MAX_ARG_STRLEN):
      # a Moss node with three apps already answers 110 KB. Only the status
      # is read from it there.
      app_status=$(printf '%s' "$apps" | jq -c 'if type == "array" then [.[] | {status: {type: .status.type}}] else . end')

      # Gossip and fetch state for every DHT the conductor is in, keyed by DNA
      # hash; list-apps names the app and role each DNA belongs to. null when
      # the call fails, and dht-metrics.jq then writes no per-DHT series.
      if ! { dht=$(timeout 15 ${callPrefix} dump-network-metrics --include-dht-summary 2>/dev/null) \
        && printf '%s' "$dht" | jq -e 'type == "object"' > /dev/null 2>&1; }; then
        dht=null
      fi

      # The reply counts bytes and messages per open connection only, so the
      # running totals live here between runs (see conductor-counters.jq). A
      # missing or unreadable file starts them from zero, which Prometheus
      # reads as the counter reset it is.
      state=${lib.escapeShellArg conductorCountersFile}
      prev=$(cat "$state" 2>/dev/null || true)
      if ! printf '%s' "$prev" | jq -e 'type == "object"' > /dev/null 2>&1; then
        prev='{}'
      fi
      counters=$(printf '%s' "$stats" | jq -c --argjson prev "$prev" -f ${./conductor-counters.jq})
      printf '%s\n' "$counters" > "$state.tmp"
      mv -f "$state.tmp" "$state"

      now=$(date +%s)
      printf '%s' "$stats" \
        | jq -r --argjson up "$up" --argjson now "$now" \
            --argjson totals "$(printf '%s' "$counters" | jq -c .totals)" \
            --argjson apps "$app_status" \
            -f ${./conductor-metrics.jq} > "$tmp"

      # Appended only when jq finished cleanly: a reply of a shape it did not
      # expect must cost the per-DHT series, never the conductor series above
      # or the file as a whole. Both replies go through stdin (see
      # dht-metrics.jq for why not --argjson).
      if printf '%s\n%s\n' "$apps" "$dht" \
        | jq -n -r --argjson now "$now" -f ${./dht-metrics.jq} > "$tmp.dht"; then
        cat "$tmp.dht" >> "$tmp"
      else
        echo "dht-metrics.jq failed; per-DHT series left out of this run" >&2
      fi
      rm -f "$tmp.dht"

      # The collector may read the directory at any moment, so the file is
      # swapped in whole rather than truncated and rewritten in place.
      mv -f "$tmp" "$out"
    '';
  };
in {
  options.services.holochain-edgenode = {
    enable = lib.mkEnableOption "Holochain edgenode (conductor + lair + hApp installer)";

    package = lib.mkOption {
      type = lib.types.package;
      default = inputs.holonix.packages.${pkgs.stdenv.hostPlatform.system}.holochain;
      defaultText = lib.literalExpression "inputs.holonix.packages.\${pkgs.stdenv.hostPlatform.system}.holochain";
      description = ''
        Holochain conductor package. Its `version` selects the config schema the
        module renders: below 0.7 the network section carries `bootstrap_url`,
        `signal_url` and `relay_url`; from 0.7 it carries `bootstrap_url` and
        `relay_url`, because `signal_url` was removed from the schema.
      '';
    };

    hcPackage = lib.mkOption {
      type = lib.types.package;
      default = inputs.holonix.packages.${pkgs.stdenv.hostPlatform.system}.hc;
      defaultText = lib.literalExpression "inputs.holonix.packages.\${pkgs.stdenv.hostPlatform.system}.hc";
      description = ''
        Holochain CLI package used by the hApp installer. Keep it on the same
        line as `package`: the admin subcommand is `hc client call` from 0.7 and
        `hc sandbox call` below it.
      '';
    };

    user = lib.mkOption {
      type = lib.types.str;
      default = "holochain";
      description = "System user the conductor runs as.";
    };

    dataDir = lib.mkOption {
      type = lib.types.path;
      default = "/var/lib/holochain";
      description = ''
        Persistent state directory for the conductor database, the lair keystore
        and the generated passphrase. Created as the unit's `StateDirectory` with
        mode 0700.

        Keep it short. The keystore's unix socket is `''${dataDir}/ks/socket` and
        unix socket paths are capped at 108 bytes (`SUN_LEN`); a deeper path makes
        the conductor exit at startup with `path must be shorter than SUN_LEN`.
      '';
    };

    passphraseFileName = lib.mkOption {
      type = lib.types.str;
      default = "lair-passphrase";
      description = ''
        Name of the lair passphrase file inside `dataDir`. Generated with mode
        0600 on first boot if absent and reused on every boot after that, which
        is what lets the keystore open again after a reboot with nobody present.
      '';
    };

    adminPort = lib.mkOption {
      type = lib.types.port;
      default = 4444;
      description = "WebSocket port for the conductor admin interface (bound to localhost).";
    };

    appPort = lib.mkOption {
      type = lib.types.port;
      default = 8888;
      description = "WebSocket port the hApp installer attaches as the app interface.";
    };

    allowedOrigins = lib.mkOption {
      type = lib.types.str;
      default = "*";
      description = ''
        Allowed origins for the app WebSocket interface the installer attaches:
        `*`, a single origin, or a comma-separated list.
      '';
    };

    adminAllowedOrigins = lib.mkOption {
      type = lib.types.str;
      default = "holochain_websocket";
      description = ''
        Allowed origins for the admin WebSocket interface. The default is the
        Origin header `hc` sends when given no `--origin`, which is what the
        hApp installer and the metrics timer use, and which no browser sends:
        with `*` any web page open in a browser on the node could drive the
        admin API over `ws://localhost`. Widen it only for an admin UI you
        trust.
      '';
    };

    bootstrapUrl = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      description = ''
        Kitsune2 bootstrap server used for WAN peer discovery. `null` selects the
        default for the configured line: `https://dev-test-bootstrap2.holochain.org`
        below 0.7 (Holo-Host/edgenode's 0.6.1 template) and the same URL with a
        trailing slash from 0.7 (what `holochain --create-config` writes). No
        production bootstrap URL is documented for either line, so point this at
        your own infrastructure for a real deployment.
      '';
    };

    signalUrl = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      description = ''
        WebRTC signal server. Used only below 0.7, where `null` selects
        `wss://dev-test-bootstrap2.holochain.org`. `network.signal_url` was
        removed from the 0.7 config schema, so from 0.7 this option is ignored
        and setting it raises a warning; use `relayUrl` instead.
      '';
    };

    relayUrl = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      description = ''
        Iroh relay used when a direct connection cannot be established. Required
        by the conductor on both lines; `null` selects
        `https://use1-1.relay.n0.iroh-canary.iroh.link./`, the default both
        0.6.3 and 0.7.0 write for themselves.

        For a `services.holochain-bootstrap` server this is
        `http(s)://<host>:<port>/relay`: the same server as `bootstrapUrl`,
        on the `/relay` path. A plain `http://` relay also needs
        `relayAllowPlainText`.
      '';
    };

    relayAllowPlainText = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Let the iroh transport use a plain-HTTP relay, by rendering
        `network.advanced.irohTransport.relayAllowPlainText: true`. Kitsune2
        refuses an `http://` relay URL without it, so the conductor would not
        start. Needed for a LAN `services.holochain-bootstrap` server without
        TLS; leave it off for an `https://` relay. Works on both lines.
      '';
    };

    requestTimeoutS = lib.mkOption {
      type = lib.types.nullOr lib.types.ints.positive;
      default = null;
      example = 90;
      description = ''
        `network.request_timeout_s`: seconds before a request and its response
        time out. `null` leaves the conductor default, 60. Same key on both
        lines.
      '';
    };

    dbSyncLevel = lib.mkOption {
      type = lib.types.nullOr (lib.types.enum ["Full" "Normal" "Off"]);
      default = null;
      description = ''
        `db_sync_level`, the SQLite synchronous level, from 0.7 only (0.6 has
        `db_sync_strategy` instead, which this module does not set). `null`
        leaves the conductor default, `Normal`. `Off` trades crash safety for
        speed. Ignored with a warning below 0.7.
      '';
    };

    wasmBackend = lib.mkOption {
      type = lib.types.nullOr (lib.types.enum ["cranelift" "LLVM" "wasmi"]);
      default = null;
      description = ''
        `wasm_backend`, from 0.7 only: which compiler runs zomes when the
        Holochain binary was built with more than one. The conductor refuses a
        backend it was not built with. `null` uses whichever is available.
        Ignored with a warning below 0.7.
      '';
    };

    conductorConfigFile = lib.mkOption {
      type = lib.types.path;
      readOnly = true;
      internal = true;
      description = "The rendered conductor config, exposed so checks can read it.";
    };

    installerTimeout = lib.mkOption {
      type = lib.types.int;
      default = 300;
      description = ''
        Seconds the hApp installer allows each of its waits: the admin interface
        answering at all, then, per hApp, the install and the enable settling.
        The conductor needs about 80 seconds to open the port on an
        unaccelerated VM, so leave room. The unit itself has no start timeout,
        so raising this is enough.
      '';
    };

    useSystemdNotify = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Run the conductor as `Type = "notify"`, so the unit becomes active only
        once the conductor has signalled readiness rather than as soon as the
        process exists. Set to false to fall back to `Type = "simple"`.
      '';
    };

    happs = lib.mkOption {
      type = lib.types.attrsOf (lib.types.submodule {
        options = {
          src = lib.mkOption {
            type = lib.types.path;
            description = "Path to the `.happ` bundle. Fetch it by hash; never commit one (ADR-012).";
          };
          installed = lib.mkOption {
            type = lib.types.bool;
            default = true;
            description = ''
              Whether to install this hApp when absent and keep it enabled.
              Setting it to false (or removing the entry) stops managing the
              app; it does not disable or uninstall an app already installed.
            '';
          };
          networkSeed = lib.mkOption {
            type = lib.types.nullOr lib.types.str;
            default = null;
            description = "Network seed override for every DNA in this app.";
          };
        };
      });
      default = {};
      description = "hApps to install and keep enabled, keyed by installed app id.";
      example = lib.literalExpression ''
        {
          dino-adventure = {
            src = pkgs.fetchurl {
              url = "https://github.com/holochain/dino-adventure/releases/download/v0.3.0/dino-adventure-v0.3.0.happ";
              sha256 = "...";
            };
            networkSeed = "workshop-2026";
          };
        }
      '';
    };

    metricsExporter = {
      enable = lib.mkEnableOption "Prometheus node_exporter for fleet observability";

      port = lib.mkOption {
        type = lib.types.port;
        default = 9100;
        description = "Port to expose node metrics on.";
      };

      textfileDirectory = lib.mkOption {
        type = lib.types.path;
        default = "/var/lib/prometheus-node-exporter-text-files";
        description = ''
          Directory node_exporter's textfile collector reads. Every `*.prom`
          file in it is appended to `/metrics` verbatim, which is how metrics
          that no exporter produces on its own reach Prometheus.

          The directory is created 0755 and owned by `user`, so the conductor
          metrics timer can write into it while node_exporter, which runs as
          its own user, can read it.
        '';
      };
    };

    conductorMetrics = {
      enable = lib.mkEnableOption ''
        a timer that exports the conductor's own network stats as
        `holochain_*` series through node_exporter's textfile collector.

        This is the fleet dashboard's Holochain data source. It calls
        `dump-network-stats` on the admin interface, which answers with
        Kitsune2's `TransportStats` on both the 0.6 and 0.7 lines, and derives
        connection gauges and byte and message counters from it; it also
        counts installed apps by status from `list-apps`. The counters are
        running totals kept in `conductor-metrics-counters.json` under
        `dataDir`, so a peer disconnecting does not pull them down. It also
        calls `dump-network-metrics --include-dht-summary` and writes one
        `holochain_dht_*` series set per DHT the conductor is in (peers, ops
        held here and by the best peer, pending fetches, seconds since the
        last gossip, completed rounds and timeouts), labelled `app`, `role`
        and `dna`. Requires `metricsExporter.enable`
      '';

      interval = lib.mkOption {
        type = lib.types.str;
        default = "30s";
        example = "1min";
        description = ''
          How often the timer writes the textfile, as a systemd time span. The
          floor is what the dashboard's resolution is worth: Prometheus scrapes
          node_exporter on its own schedule and simply re-reads whatever the
          file last said, so a value far above the scrape interval shows as a
          staircase rather than a curve.
        '';
      };
    };

    binaryCache.enable = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Declare the Holochain Foundation's binary cache
        (`https://holochain-ci.cachix.org`) in the host's `nix.settings`, so
        `holochain` and `hc` are downloaded prebuilt instead of compiled from
        source. A flake's own `nixConfig` does not reach a downstream flake
        that imports this module, and without the cache a first
        `nixos-rebuild switch` compiles the whole Holochain workspace
        (seen on a homelab rehearsal, 2026-09-26).

        The setting lands in `nix.conf` only once a switch has activated it,
        so the very first switch that brings it still builds from source
        unless it is run with
        `--option extra-substituters https://holochain-ci.cachix.org
        --option extra-trusted-public-keys <key>`; see docs/deployment.md.
      '';
    };

    openFirewall = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Open firewall ports for the app and metrics interfaces. The admin port
        is never opened. The conductor binds its websockets to localhost, so in
        practice this matters for the metrics exporter, and for the app port
        only if `danger_bind_addr` is configured by hand.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    services.holochain-edgenode.conductorConfigFile = conductorConfig;

    warnings =
      lib.optional (!isPre07 && cfg.signalUrl != null)
      "services.holochain-edgenode.signalUrl is set, but network.signal_url was removed from the Holochain 0.7 config schema and is ignored. Use services.holochain-edgenode.relayUrl instead."
      ++ lib.optional (isPre07 && cfg.dbSyncLevel != null)
      "services.holochain-edgenode.dbSyncLevel is set, but db_sync_level exists only from Holochain 0.7 and is ignored on ${cfg.package.version}."
      ++ lib.optional (isPre07 && cfg.wasmBackend != null)
      "services.holochain-edgenode.wasmBackend is set, but wasm_backend exists only from Holochain 0.7 and is ignored on ${cfg.package.version}.";

    nix.settings = lib.mkIf cfg.binaryCache.enable {
      extra-substituters = ["https://holochain-ci.cachix.org"];
      extra-trusted-public-keys = ["holochain-ci.cachix.org-1:5IUSkZc0aoRS53rfkvH9Kid40NpyjwCMCzwRTXy+QN8="];
    };

    users.users.${cfg.user} = {
      isSystemUser = true;
      group = cfg.user;
      home = cfg.dataDir;
    };
    users.groups.${cfg.user} = {};

    systemd.services.holochain-conductor = {
      description = "Holochain conductor";
      wantedBy = ["multi-user.target"];
      after = ["network-online.target"];
      wants = ["network-online.target"];

      # ADR-016: the passphrase is generated into the state directory, never into
      # the Nix store, so it survives a reboot and never becomes world-readable.
      preStart = ''
        umask 077
        if [ ! -s ${lib.escapeShellArg passphraseFile} ]; then
          echo "generating a new lair passphrase at ${passphraseFile}"
          head -c 32 /dev/urandom | base64 | tr -d '\n' > ${lib.escapeShellArg passphraseFile}
          chmod 0600 ${lib.escapeShellArg passphraseFile}
        else
          echo "using the existing lair passphrase at ${passphraseFile}"
        fi
      '';

      script = ''
        exec ${lib.getExe' cfg.package "holochain"} \
          --piped \
          --config-path ${conductorConfig} \
          < ${lib.escapeShellArg passphraseFile}
      '';

      serviceConfig =
        {
          User = cfg.user;
          Group = cfg.user;
          StateDirectory = stateDirectory;
          StateDirectoryMode = "0700";
          WorkingDirectory = cfg.dataDir;
          Restart = "on-failure";
          RestartSec = "5s";
          UMask = "0077";
        }
        // (
          if cfg.useSystemdNotify
          then {
            Type = "notify";
            NotifyAccess = "all";
            # The conductor takes well over a minute to come up on an
            # unaccelerated VM; the default 90s would kill it mid-startup.
            TimeoutStartSec = "600s";
          }
          else {Type = "simple";}
        );
    };

    systemd.services.holochain-happ-installer = lib.mkIf (cfg.happs != {}) {
      description = "Install and enable the configured hApps in the Holochain conductor";
      after = ["holochain-conductor.service"];
      requires = ["holochain-conductor.service"];
      wantedBy = ["multi-user.target"];

      serviceConfig = {
        Type = "oneshot";
        User = cfg.user;
        Group = cfg.user;
        WorkingDirectory = cfg.dataDir;
        RemainAfterExit = true;
        ExecStart = lib.getExe happInstaller;
        # The script bounds each of its waits by installerTimeout, and there
        # are two per hApp plus the readiness wait, so a fixed unit timeout
        # would cut raising installerTimeout off at an arbitrary total.
        TimeoutStartSec = "infinity";
      };
    };

    assertions = [
      {
        assertion = lib.hasPrefix "/var/lib/" (toString cfg.dataDir);
        message = ''
          services.holochain-edgenode.dataDir must live under /var/lib/: it is
          created as the units' systemd StateDirectory, which systemd only
          creates there. Got ${toString cfg.dataDir}.
        '';
      }
      {
        # kitsune2's iroh transport rejects the config with "Disallowed
        # plaintext relay URL" (transport_iroh `validate_config`, v0.4.1), and
        # the conductor never comes up; better to fail at evaluation.
        assertion = lib.hasPrefix "http://" relayUrl -> cfg.relayAllowPlainText;
        message = ''
          services.holochain-edgenode.relayUrl is plain HTTP (${relayUrl}),
          which the conductor refuses unless
          services.holochain-edgenode.relayAllowPlainText = true.
        '';
      }
      {
        assertion = cfg.conductorMetrics.enable -> cfg.metricsExporter.enable;
        message = ''
          services.holochain-edgenode.conductorMetrics.enable needs
          services.holochain-edgenode.metricsExporter.enable: the conductor
          gauges are published through node_exporter's textfile collector, so
          without the exporter the timer would write a file nothing reads.
        '';
      }
    ];

    services.prometheus.exporters.node = lib.mkIf cfg.metricsExporter.enable {
      enable = true;
      port = cfg.metricsExporter.port;
      enabledCollectors = ["systemd" "textfile"];
      extraFlags = [
        "--collector.textfile.directory=${textfileDir}"
        # node_exporter leaves mount and automount units out by default, so a
        # data disk that fails to mount would never reach the dashboard's
        # failed-unit count. Kept in step with holochain-grafana, which sets
        # the same flag at mkDefault for a monitor that is not an edgenode:
        # node_exporter refuses to start when the flag is given twice.
        "--collector.systemd.unit-exclude=${systemdUnitExclude}"
      ];
    };

    systemd.tmpfiles.rules = lib.mkIf cfg.metricsExporter.enable [
      "d ${textfileDir} 0755 ${cfg.user} ${cfg.user} - -"
    ];

    systemd.services.holochain-conductor-metrics = lib.mkIf cfg.conductorMetrics.enable {
      description = "Export Holochain conductor network stats to the node_exporter textfile collector";
      after = ["holochain-conductor.service"];

      # Deliberately not `requires`: the point of the exporter is to keep
      # reporting while the conductor is down, as holochain_conductor_up 0.

      environment.HOME = cfg.dataDir;

      serviceConfig = {
        Type = "oneshot";
        User = cfg.user;
        Group = cfg.user;
        StateDirectory = stateDirectory;
        StateDirectoryMode = "0700";
        WorkingDirectory = cfg.dataDir;
        ExecStart = lib.getExe conductorMetricsScript;
        TimeoutStartSec = "60s";
      };
    };

    systemd.timers.holochain-conductor-metrics = lib.mkIf cfg.conductorMetrics.enable {
      description = "Periodic export of Holochain conductor network stats";
      wantedBy = ["timers.target"];
      timerConfig = {
        OnBootSec = cfg.conductorMetrics.interval;
        OnUnitActiveSec = cfg.conductorMetrics.interval;
        AccuracySec = "1s";
        Unit = "holochain-conductor-metrics.service";
      };
    };

    networking.firewall = lib.mkIf cfg.openFirewall {
      allowedTCPPorts =
        [cfg.appPort]
        ++ lib.optional cfg.metricsExporter.enable cfg.metricsExporter.port;
    };
  };
}
