# A fleet of Holochain edgenodes: five nodes, node-01 doubling as the Grafana
# monitor, plus a live ISO to install them from.
#
# Generated by `nix flake init -t github:Sensorica/nixos-holochain#fleet`.
# Rename the hosts under hosts/ to match your machines, replace each
# hardware-configuration.nix with real output from that machine, then
#   sudo nixos-rebuild switch --flake .#node-01     # one machine
#   nix develop && colmena apply --impure --on @all # the whole fleet
{
  description = "A fleet of Holochain edgenodes built with nixos-holochain";

  inputs = {
    nixos-holochain.url = "github:Sensorica/nixos-holochain";
    # The fleet pins its own nixpkgs, as any downstream fleet does; the
    # Holochain toolchain comes from the module repository.
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-25.05";
    # The edgenode module takes its default conductor and `hc` packages from
    # `inputs.holonix`. Following the module repository keeps the fleet on the
    # Holochain line the modules are tested against (0.7); point it at
    # `github:holochain/holonix/main-0.6` instead to run the 0.6 line.
    holonix.follows = "nixos-holochain/holonix";
  };

  outputs = inputs @ {
    nixpkgs,
    nixos-holochain,
    ...
  }: let
    system = "x86_64-linux";
    inherit (nixpkgs) lib;
    pkgs = import nixpkgs {inherit system;};

    hosts = ["node-01" "node-02" "node-03" "node-04" "node-05"];

    # Passed to every host: the module reads inputs.holonix for its packages.
    specialArgs = {inherit inputs;};

    fleetModules = [
      nixos-holochain.nixosModules.holochain-edgenode
      nixos-holochain.nixosModules.holochain-grafana
      # Imported so hosts/common.nix can turn it off in writing rather than by
      # omission; see the comment there.
      nixos-holochain.nixosModules.holochain-windtunnel
    ];

    mkNode = name:
      lib.nixosSystem {
        inherit system specialArgs;
        modules = fleetModules ++ [./hosts/${name}/configuration.nix];
      };
  in {
    nixosConfigurations =
      lib.genAttrs hosts mkNode
      // {
        # Bootable live ISO to install the fleet from.
        live-iso = lib.nixosSystem {
          inherit system;
          modules = [./hosts/live-iso/configuration.nix];
        };
      };

    # Colmena hive: `colmena apply --impure --on @all` from this directory.
    colmena =
      {
        meta = {
          nixpkgs = pkgs;
          inherit specialArgs;
        };
      }
      // lib.genAttrs hosts (name: {
        imports = fleetModules ++ [./hosts/${name}/configuration.nix];
      });

    devShells.${system}.default = pkgs.mkShell {
      buildInputs = with pkgs; [colmena nixos-rebuild alejandra];
    };
  };
}
