# A single Holochain edgenode, declared in NixOS.
#
# Generated by `nix flake init -t github:Sensorica/nixos-holochain#minimal`.
# Edit configuration.nix, replace hardware-configuration.nix with the output of
# `nixos-generate-config --show-hardware-config` run on the target machine, then
#   sudo nixos-rebuild switch --flake .#edgenode
{
  description = "A Holochain edgenode built with nixos-holochain";

  inputs = {
    nixos-holochain.url = "github:Sensorica/nixos-holochain";
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-25.05";
    # The edgenode module takes its default conductor and `hc` packages from
    # `inputs.holonix`, so an input under that name has to reach it. Following
    # the module repository keeps this node on the Holochain line the modules
    # are tested against (0.7); point it at `github:holochain/holonix/main-0.6`
    # instead to run the 0.6 line.
    holonix.follows = "nixos-holochain/holonix";
  };

  outputs = inputs @ {
    nixpkgs,
    nixos-holochain,
    ...
  }: {
    nixosConfigurations.edgenode = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      # The module reads `inputs.holonix`; specialArgs is how it gets there.
      specialArgs = {inherit inputs;};
      modules = [
        nixos-holochain.nixosModules.holochain-edgenode
        ./configuration.nix
      ];
    };
  };
}
